modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="seasonhud"
version="1.0"
displayName="Season Info HUD"
displayURL="http://google.com"
authors="Worador"
description='''
Ein HUD das die aktuellen Serene Seasons Informationen anzeigt.
'''

[[dependencies.seasonhud]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.seasonhud]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2]"
ordering="NONE"
side="BOTH"

[[dependencies.seasonhud]]
modId="sereneseasons"
mandatory=true
versionRange="[8.1.0,)"
ordering="AFTER"
side="BOTH"